### ISSUE TITLE
012.002 Relevar los informes financieros obligatorios de la legislacion Argentina

### ISSUE THREAD

**Issue by martinllanos** [cumbreges/l10n_ar_mis_report#2]
## Problema: 
Mis Builder Report AR no cuenta con los informes financieros correspondientes a normas vigentes. Estos reportes tienen que incluir una preforma con campos variables para que se completen con la informacion de Odoo de forma automatica y de forma inteligente.
## Solucion:
Relevar cuales son los informes financieros vigentes para elaborar un roadmap de desarrollo de cada uno de ellos.

* Informes actuales

<table>
        <thead>
          <tr>
            <th colspan="3"><h2>NORMAS NACIONALES/INTERNACIONALES</h2></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><h3>NORMAS LOCALES</h3></td>
            <td><h3>NIIF COMPLETAS</h3></td>
            <td><h3>NIIF PARA PYMES</h3></td>
          </tr>
          <tr>
            <td>Estado de situacion patrimonial</td>
            <td>Estado de situación financiera</td>
            <td>Estado de situación financiera</td>
          </tr>
          <tr>
            <td>Estado de Resultados</td>
            <td>Estado de resultado integral y Estado de resultados</td>
            <td>Estado de resultado integral y Estado de resultados</td>
          </tr>
          <tr>
            <td>Estado de Evolución del Patrimonio Neto</td>
            <td>Estado de cambios en el patrimonio</td>
            <td>Estado de cambios en el patrimonio y estado de resultados y ganancias acumuladas</td>
          </tr>
          <tr>
            <td>Estado de Flujo de efectivo</td>
            <td>Estado de flujos de efectivo</td>
            <td>Estado de flujos de efectivo</td>
          </tr>
          <tr>
            <td>Información Complementaria(comprende notas a los estados contables y cuadros anexos)</td>
            <td>Notas a los estados financieros</td>
            <td>Notas a los estados financieros</td>
          </tr>
        </tbody>
      </table>

## Diagrama de flujo:

**Comment by nanosgr** [comment]
Es importante con anterioridad tener el reporte de Balance de Sumas y Saldos, para ello debe contarse con un ambiente donde en la contabilidad, se encuentre hecho el asiento inicial, y una casuistica de operaciones habituales del cliente.

**Comment by nanosgr** [comment]
Se adjunta modelo de estados contables

[Balance 2018 - Testeo SRL.xlsx](https://github.com/cumbreges/l10n_ar_mis_report/files/3962081/Balance.2018.-.Testeo.SRL.xlsx)
